import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'pl': {
      'app_title': 'Work Study Timer',
      'language': 'Język',
      'range': 'Zakres',
      'today': 'Dzisiaj',
      'this_week': 'Ten tydzień',
      'this_month': 'Ten miesiąc',
      'all': 'Wszystko',
      'search_hint': 'Szukaj po opisie (np. Margarita, Finca)',
      'instructions_title': 'Instrukcja obsługi',
      'instructions_content':
      'Work Study Timer – śledź czas, osiągaj cele!\n\n'
          '⏱️ 1. TIMER (zakładka główna)\n'
          '• Wpisz opis aktywności i wybierz kategorię\n'
          '• Naciśnij START aby rozpocząć sesję\n'
          '• Naciśnij STOP aby zapisać sesję w historii\n'
          '• Możesz też dodać sesję ręcznie – przycisk "USTAW CZAS RĘCZNIE"\n\n'
          '📊 2. PODSUMOWANIE\n'
          '• Filtruj dane: Dzisiaj / Ten tydzień / Ten miesiąc / Wszystko\n'
          '• Wykres słupkowy ostatnich 7 dni\n'
          '• Wykres kołowy podziału czasu według kategorii\n'
          '• Szczegółowe statystyki z paskami postępu\n\n'
          '🎯 3. CELE\n'
          '• Dodaj cel tygodniowy lub miesięczny\n'
          '• Ustaw liczbę godzin i kategorię\n'
          '• Śledź postęp na pasku postępu\n\n'
          '📅 4. WYDARZENIA\n'
          '• Dodaj zaplanowane wydarzenia z datą i godziną\n'
          '• Ustaw przypomnienie (5 min – tydzień przed)\n'
          '• Kategorie: Praca, Sport, Czas wolny, Inne\n\n'
          '🍅 5. POMODORO\n'
          '• Technika Pomodoro: 25 min pracy + 5 min przerwy\n'
          '• Dostosuj czasy pracy i przerw w ustawieniach\n'
          '• Po 4 sesjach automatyczna długa przerwa\n\n'
          '🎮 6. GRY\n'
          '• Memory Game – 10 poziomów trudności\n'
          '• Sudoku – 10 poziomów trudności\n'
          '• Odblokuj kolejne poziomy ukończając poprzednie\n\n'
          '⚙️ 7. USTAWIENIA (ikona koła zębatego)\n'
          '• Zmień tło aplikacji (własne zdjęcie)\n'
          '• Zmień kolor ikon\n'
          '• Zmień język: 🇵🇱 Polski / 🇪🇸 Español / 🇬🇧 English\n\n'
          '💾 8. BACKUP DANYCH\n'
          '• Eksportuj dane – zapisz backup na telefonie\n'
          '• Udostępnij backup – wyślij plik e-mailem lub WhatsApp\n'
          '• Importuj dane – wczytaj poprzedni backup\n\n'
          '🔒 9. PRYWATNOŚĆ\n'
          '• Wszystkie dane zapisywane są tylko lokalnie na Twoim urządzeniu',
      'work': 'Praca',
      'sport': 'Sport',
      'free_time': 'Czas wolny',
      'type': 'Kategoria',
      'type_instruction': 'Wybierz kategorię swojej aktywności',
      'add_new_type': 'Dodaj nowy typ',
      'add_custom_type_title': 'Dodaj nowy typ aktywności',
      'custom_type_hint': 'Nazwa nowej aktywności (np. Nauka, Gitara)',
      'manage_custom_types': 'Zarządzaj typami',
      'no_custom_types': 'Brak własnych typów.',
      'type_name_label': 'Nazwa typu',
      'type_exists': 'Ten typ już istnieje',
      'type_added': 'Typ dodany',
      'type_deleted': 'Typ usunięty',
      'delete_type': 'Usuń typ',
      'cannot_delete_default': 'Nie można usunąć domyślnego typu',
      'quick_timer': 'Szybki timer',
      'description_hint': 'Opis (opcjonalnie)',
      'start_btn': 'Start',
      'stop_btn': 'Stop',
      'no_active': 'Brak aktywnej sesji.',
      'close': 'Zamknij',
      'close_btn': 'Zamknij',
      'new_activity_section': 'Nowa aktywność',
      'start_now_btn': 'START TERAZ',
      'add_time_range_btn': 'USTAW CZAS RĘCZNIE',
      'running_since': 'Trwa od',
      'summary_title': 'Podsumowanie',
      'summary_total': 'Suma',
      'last_7_days': 'Ostatnie 7 dni',
      'time_distribution': 'Podział czasu',
      'detailed_summary': 'Szczegółowe podsumowanie',
      'avg_per_day': 'Średnio/dzień',
      'best_day': 'Najlepszy dzień',
      'last_30_days': 'Ostatnie 30 dni',
      'day_mon': 'Pn',
      'day_tue': 'Wt',
      'day_wed': 'Śr',
      'day_thu': 'Cz',
      'day_fri': 'Pt',
      'day_sat': 'So',
      'day_sun': 'Nd',
      'no_data': 'Brak danych',
      'date_label': 'Data: ',
      'choose_date': 'Wybierz datę',
      'description_label': 'Co będziesz robić? (np. Bieganie, Nauka)',
      'start_time_label': 'Start (HH:MM)',
      'end_time_label': 'Koniec (HH:MM)',
      'start_time_hint': 'np. 08:30',
      'end_time_hint': 'np. 10:15',
      'add_session_btn': 'Dodaj sesję',
      'no_description': 'Brak opisu',
      'error_time_format': 'Sprawdź godziny (format HH:MM, koniec po starcie).',
      'fill_all_fields': 'Wypełnij wszystkie pola',
      'invalid_time_format': 'Nieprawidłowy format czasu (użyj HH:MM)',
      'session_added': 'Sesja dodana',
      'history_title': 'Historia sesji',
      'history_empty': 'Brak sesji w wybranym zakresie.',
      'mode_manual': 'Manualnie',
      'mode_auto': 'Start/Stop',
      'edit': 'Edytuj',
      'delete': 'Usuń',
      'export': 'Eksportuj',
      'import': 'Importuj',
      'edit_session': 'Edytuj sesję',
      'edit_session_title': 'Edytuj sesję',
      'cancel': 'Anuluj',
      'cancel_btn': 'Anuluj',
      'save': 'Zapisz',
      'save_btn': 'Zapisz',
      'add_btn': 'Dodaj',
      'error_edit_time': 'Błędne godziny (format HH:MM, koniec po starcie).',
      'session_running_from': 'Trwa sesja od: ',
      'field_type': 'Typ: ',
      'field_mode': 'Tryb: ',
      'session_deleted': 'Sesja usunięta',
      'session_updated': 'Sesja zaktualizowana',
      'export_ok': 'Eksport OK: ',
      'export_error': 'Błąd eksportu: ',
      'export_success': 'Wyeksportowano do',
      'backup_missing': 'Brak pliku backup!',
      'import_ok': 'Zaimportowano sesji: ',
      'import_error': 'Błąd importu: ',
      'import_success': 'Import zakończony sukcesem',
      'no_files_to_import': 'Brak plików do importu',
      'choose_file_to_import': 'Wybierz plik do importu',
      'backup_saved': 'Backup zapisany',
      'change_background': 'Zmień tło',
      'remove_background': 'Usuń tło',
      'icon_color_picker': 'Kolor ikon',
      'slide_to_change_color': 'Przesuń suwak aby zmienić kolor',
      'goals_title': 'Moje Cele',
      'add_goal': 'Dodaj cel',
      'no_goals': 'Brak celów. Dodaj pierwszy cel!',
      'goal_name': 'Nazwa celu',
      'goal_name_hint': 'np. Nauka angielskiego',
      'goal_hours': 'Cel w godzinach',
      'goal_hours_hint': 'np. 10',
      'goal_period': 'Okres',
      'goal_week': 'Tydzień',
      'goal_month': 'Miesiąc',
      'goal_type': 'Typ',
      'goal_all_types': 'Wszystkie',
      'goal_added': 'Cel dodany!',
      'goal_deleted': 'Cel usunięty',
      'goal_completed': 'Cel osiągnięty! Świetna robota!',
      'goal_remaining': 'Jeszcze {hours}h do celu',
      'goal_progress': '{current}h / {target}h',
      'goal_invalid_hours': 'Podaj prawidłową liczbę godzin',
      'games_tab': 'Gry',
      'memory_game_title': 'Memory Game',
      'new_game': 'Nowa gra',
      'time': 'Czas',
      'moves': 'Ruchy',
      'record': 'Rekord',
      'congratulations': 'Gratulacje! 🎉',
      'game_completed': 'Ukończyłeś grę!',
      'new_time_record': '🏆 NOWY REKORD CZASU!',
      'new_moves_record': '🏆 NOWY REKORD RUCHÓW!',
      'play_again': 'Graj ponownie',
      'game_instructions': 'Znajdź wszystkie pary! Kliknij kartę aby ją odkryć.',
      'your_records': '🏆 Twoje rekordy:',
      'best_time': 'Najlepszy czas:',
      'fewest_moves': 'Najmniej ruchów:',
      'choose_game': 'Wybierz grę',
      'games_subtitle': 'Relaksuj się pomiędzy sesjami pracy',
      'memory_game_desc': 'Znajdź wszystkie pary kart!',
      'coming_soon': 'Wkrótce dostępne!',
      'memory_level_easy': 'Łatwy (4x3, 6 par)',
      'memory_level_medium': 'Średni (4x4, 8 par)',
      'memory_level_hard': 'Trudny (4x5, 10 par)',
      'memory_level_advanced': 'Zaawansowany (4x6, 12 par)',
      'memory_level_expert': 'Ekspert (5x6, 15 par)',
      'memory_level_master': 'Mistrz (5x8, 18 par)',
      'memory_level_legend': 'Legenda (5x8, 20 par)',
      'memory_level_epic': 'Epicki (5x9, 22 pary)',
      'memory_level_nightmare': 'Koszmar (5x10, 24 pary)',
      'memory_level_impossible': 'Niemożliwy (5x10, 25 par)',
      'memory_choose_level': 'Wybierz poziom',
      'memory_locked': 'Poziom zablokowany. Najpierw ukończ poprzedni.',
      'sudoku_game_title': 'Sudoku',
      'sudoku_game_desc': 'Wypełnij siatkę 9x9 cyframi!',
      'sudoku_choose_level': 'Wybierz poziom Sudoku',
      'sudoku_level_1': 'Poziom 1 - Początkujący',
      'sudoku_level_2': 'Poziom 2 - Łatwy',
      'sudoku_level_3': 'Poziom 3 - Średni łatwy',
      'sudoku_level_4': 'Poziom 4 - Średni',
      'sudoku_level_5': 'Poziom 5 - Średni trudny',
      'sudoku_level_6': 'Poziom 6 - Trudny',
      'sudoku_level_7': 'Poziom 7 - Bardzo trudny',
      'sudoku_level_8': 'Poziom 8 - Ekspert',
      'sudoku_level_9': 'Poziom 9 - Mistrz',
      'sudoku_level_10': 'Poziom 10 - Niemożliwy',
      'sudoku_locked': 'Poziom zablokowany. Najpierw ukończ poprzedni.',
      'sudoku_congratulations': 'Sudoku ukończone! 🎉',
      'sudoku_new_game': 'Nowa gra',
      'sudoku_check': 'Sprawdź',
      'sudoku_errors': 'Błędy',
      'sudoku_hint': 'Podpowiedź',
      'sudoku_hints_left': 'Podpowiedzi',
      'sudoku_solved': 'Rozwiązano!',
      'sudoku_mistake': 'Błąd! Spróbuj ponownie.',
      'sudoku_best_time': 'Najlepszy czas',
      'events_tab': 'Wydarzenia',
      'events_title': 'Kalendarz Wydarzeń',
      'add_event': 'Dodaj wydarzenie',
      'no_events': 'Brak zaplanowanych wydarzeń',
      'event_title': 'Tytuł wydarzenia',
      'event_title_hint': 'np. Spotkanie, Trening',
      'event_date': 'Data i godzina',
      'event_category': 'Kategoria',
      'event_notes': 'Notatki',
      'event_notes_hint': 'Dodatkowe informacje (opcjonalnie)',
      'event_reminder': 'Przypomnienie',
      'event_category_other': 'Inne',
      'event_category_custom': 'Wpisz nazwę kategorii',
      'event_category_custom_hint': 'np. Spotkanie, Nauka, Zakupy',
      'event_added': 'Wydarzenie dodane!',
      'event_updated': 'Wydarzenie zaktualizowane',
      'event_deleted': 'Wydarzenie usunięte',
      'reminder_before': 'przed',
      'reminder_day': 'dzień przed',
      'reminder_2days': '2 dni przed',
      'reminder_week': 'tydzień przed',
      'start_from_event': 'START z wydarzenia',
      'today_events': 'Dziś',
      'upcoming_events': 'Nadchodzące',
      'past_events': 'Przeszłe',
      'pomodoro_tab': 'Pomodoro',
      'pomodoro_title': 'Timer Pomodoro',
      'pomodoro_work': 'Praca',
      'pomodoro_break': 'Przerwa',
      'pomodoro_long_break': 'Długa przerwa',
      'pomodoro_start': 'Start',
      'pomodoro_pause': 'Pauza',
      'pomodoro_reset': 'Reset',
      'pomodoro_sessions': 'Sesje',
      'pomodoro_settings': 'Ustawienia',
      'pomodoro_work_time': 'Czas pracy (min)',
      'pomodoro_break_time': 'Czas przerwy (min)',
      'pomodoro_long_break_time': 'Długa przerwa (min)',
      'pomodoro_sessions_until_long': 'Sesji do długiej przerwy',
      'pet_tab': 'Pet',
      'pet_title': 'DevPet 🐾',
      'pet_feed_btn': 'Nakarm',
      'pet_daily_xp': 'Dzienny XP',
      'pet_daily_max': '✅ Max!',
      'pet_daily_tip': '1 XP za każde 5 min nauki. Max 100 XP dziennie.',
      'pet_daily_done': '🎉 Świetna robota! Jutro możesz zdobyć kolejne XP.',
      'pet_stats_total_xp': 'Łączne XP',
      'pet_stats_collection': 'Kolekcja',
      'pet_stats_stage': 'Etap',
      'pet_rewards_title': 'Nagrody za kolekcję',
      'pet_tips_title': 'Jak to działa?',
      'pet_tip_1': 'Pracuj/ucz się — za każde 5 minut dostajesz 1 XP',
      'pet_tip_2': 'Max 100 XP dziennie — limit resetuje się o północy',
      'pet_tip_3': 'Po 1000 XP maskotka przechodzi na emeryturę',
      'pet_tip_4': 'Zbierz wszystkie 10 maskotek i odblokuj nagrody!',
      'pet_tip_5': 'Karm maskotkę — energia spada gdy nie pracujesz',
      'pet_collection_title': '🏆 Kolekcja Maskotek',
      'pet_collection_current': 'Aktualny',
      'pet_reward_unlocked': '🎊 Nagroda odblokowana!',
      'pet_reward_btn': 'Super! 🎉',
      'pet_snack_fed': 'nakarmiony! +15 energii 🍎',
      'pet_limit_reached': '😴 Limit XP na dziś osiągnięty!',
      'pet_stage_egg': 'Jajko',
      'pet_stage_baby': 'Niemowlę',
      'pet_stage_junior': 'Junior',
      'pet_stage_senior': 'Senior',
      'pet_stage_master': 'Mistrz',
      'pet_stage_retired': 'Emeryt',
      'pet_enable_title': 'Włącz DevPet',
      'pet_enable_subtitle': 'Opiekuj się wirtualną maskotką i zdobywaj XP za naukę',
      'pet_enable_btn': 'Włącz DevPet 🐾',
      'notes_tab': 'Notatnik Głosowy',
      'notes_edit_title': '✏️ Edytuj notatkę',
      'notes_cancel': 'Anuluj',
      'notes_save': 'Zapisz',
      'notes_delete_all': 'Usuń wszystkie?',
      'notes_delete_confirm': 'Tej operacji nie można cofnąć.',
      'notes_delete_btn': 'Usuń',
      'notes_recording': 'Nagrywam...',
      'notes_ready': 'Gotowy do nagrania',
      'notes_tap_to_record': 'Naciśnij mikrofon i mów...',
      'notes_tap_to_stop': 'Dotknij aby zatrzymać',
      'notes_tap_to_start': 'Dotknij aby nagrać',
      'notes_empty': 'Brak notatek.\nNaciśnij mikrofon aby dodać pierwszą.',
      'notes_reminder_set': '🔔 Przypomnienie:',
      'notes_reminder_cancel': '🔕 Przypomnienie anulowane',
      'notes_reminder_tooltip_set': 'Ustaw przypomnienie',
      'notes_reminder_tooltip_cancel': 'Anuluj przypomnienie',
      'reminder_mode_title': 'Tryb przypomnienia',
      // ── ALARM ──────────────────────────────────────────────
      'alarm_pick_title': 'Wybierz dźwięk alarmu',
      'alarm_pick_cancel': 'Anuluj',
      'alarm_pick_select': 'Wybierz',
      'alarm_reminder_title': '🔔 Przypomnienie',
      'alarm_stop': 'STOP',
      'alarm_test_tooltip': 'Testuj alarm',
      'alarm_sound_label': 'Dźwięk: ',
      'event_reminder_none': 'Brak przypomnienia',
      'event_mode_notification': 'Powiad.',
      'event_mode_vibration': 'Wibr.',
      'event_mode_alarm': 'Alarm',
      'event_mode_desc_notification': '🔔 Krótki dźwięk systemowy',
      'event_mode_desc_vibration': '📳 Tylko wibracja, bez dźwięku',
      'event_mode_desc_alarm': '🚨 Alarm w pętli — działa nawet gdy app jest zamknięta',
      'notification_channel_reminders': 'Przypomnienia',
      'notification_channel_reminders_desc': 'Powiadomienia o wydarzeniach',
      'stats_refreshed': 'Statystyki odświeżone',
      'refresh_tooltip': 'Odśwież',
      'edit_event': 'Edytuj wydarzenie',
    },

    'es': {
      'app_title': 'Work Study Timer',
      'language': 'Idioma',
      'range': 'Rango',
      'today': 'Hoy',
      'this_week': 'Esta semana',
      'this_month': 'Este mes',
      'all': 'Todo',
      'search_hint': 'Buscar por descripción (p. ej. Margarita, Finca)',
      'instructions_title': 'Instrucciones de uso',
      'instructions_content':
      'Work Study Timer – ¡controla tu tiempo, alcanza tus metas!\n\n'
          '⏱️ 1. TIMER (pestaña principal)\n'
          '• Escribe una descripción y elige la categoría\n'
          '• Pulsa START para iniciar la sesión\n'
          '• Pulsa STOP para guardar la sesión en el historial\n'
          '• También puedes añadir una sesión manual – botón "AÑADIR HORA MANUALMENTE"\n\n'
          '📊 2. RESUMEN\n'
          '• Filtra datos: Hoy / Esta semana / Este mes / Todo\n'
          '• Gráfico de barras de los últimos 7 días\n'
          '• Gráfico circular de distribución del tiempo por categoría\n'
          '• Estadísticas detalladas con barras de progreso\n\n'
          '🎯 3. OBJETIVOS\n'
          '• Añade un objetivo semanal o mensual\n'
          '• Establece el número de horas y la categoría\n'
          '• Sigue el progreso en la barra de progreso\n\n'
          '📅 4. EVENTOS\n'
          '• Añade eventos planificados con fecha y hora\n'
          '• Configura recordatorio (5 min – 1 semana antes)\n'
          '• Categorías: Trabajo, Deporte, Tiempo libre, Otro\n\n'
          '🍅 5. POMODORO\n'
          '• Técnica Pomodoro: 25 min de trabajo + 5 min de descanso\n'
          '• Personaliza los tiempos en los ajustes\n'
          '• Tras 4 sesiones, descanso largo automático\n\n'
          '🎮 6. JUEGOS\n'
          '• Juego de Memoria – 10 niveles de dificultad\n'
          '• Sudoku – 10 niveles de dificultad\n'
          '• Desbloquea nuevos niveles completando los anteriores\n\n'
          '⚙️ 7. AJUSTES (icono de engranaje)\n'
          '• Cambia el fondo de la app (foto propia)\n'
          '• Cambia el color de los iconos\n'
          '• Cambia el idioma: 🇵🇱 Polski / 🇪🇸 Español / 🇬🇧 English\n\n'
          '💾 8. COPIA DE SEGURIDAD\n'
          '• Exportar datos – guarda la copia en el teléfono\n'
          '• Compartir copia – envía el archivo por email o WhatsApp\n'
          '• Importar datos – carga una copia anterior\n\n'
          '🔒 9. PRIVACIDAD\n'
          '• Todos los datos se guardan solo localmente en tu dispositivo',
      'work': 'Trabajo',
      'sport': 'Deporte',
      'free_time': 'Tiempo libre',
      'type': 'Categoría',
      'type_instruction': 'Elige la categoría de tu actividad',
      'add_new_type': 'Añadir nuevo tipo',
      'add_custom_type_title': 'Añadir nuevo tipo de actividad',
      'custom_type_hint': 'Nombre de la nueva actividad',
      'manage_custom_types': 'Gestionar tipos',
      'no_custom_types': 'Sin tipos personalizados.',
      'type_name_label': 'Nombre del tipo',
      'type_exists': 'Este tipo ya existe',
      'type_added': 'Tipo añadido',
      'type_deleted': 'Tipo eliminado',
      'delete_type': 'Eliminar tipo',
      'cannot_delete_default': 'No se puede eliminar el tipo predeterminado',
      'quick_timer': 'Temporizador rápido',
      'description_hint': 'Descripción (opcional)',
      'start_btn': 'Iniciar',
      'stop_btn': 'Detener',
      'no_active': 'Sin sesión activa.',
      'close': 'Cerrar',
      'close_btn': 'Cerrar',
      'new_activity_section': 'Nueva actividad',
      'start_now_btn': 'INICIAR AHORA',
      'add_time_range_btn': 'AÑADIR HORA MANUALMENTE',
      'running_since': 'Ejecutando desde',
      'summary_title': 'Resumen',
      'summary_total': 'Total',
      'last_7_days': 'Últimos 7 días',
      'time_distribution': 'Distribución del tiempo',
      'detailed_summary': 'Resumen detallado',
      'avg_per_day': 'Media/día',
      'best_day': 'Mejor día',
      'last_30_days': 'Últimos 30 días',
      'day_mon': 'Lun',
      'day_tue': 'Mar',
      'day_wed': 'Mié',
      'day_thu': 'Jue',
      'day_fri': 'Vie',
      'day_sat': 'Sáb',
      'day_sun': 'Dom',
      'no_data': 'Sin datos',
      'date_label': 'Fecha: ',
      'choose_date': 'Elegir fecha',
      'description_label': '¿Qué vas a hacer? (ej. Correr, Estudiar)',
      'start_time_label': 'Inicio (HH:MM)',
      'end_time_label': 'Fin (HH:MM)',
      'start_time_hint': 'ej. 08:30',
      'end_time_hint': 'ej. 10:15',
      'add_session_btn': 'Añadir sesión',
      'no_description': 'Sin descripción',
      'error_time_format': 'Revisa las horas (formato HH:MM).',
      'fill_all_fields': 'Completa todos los campos',
      'invalid_time_format': 'Formato de tiempo inválido (usa HH:MM)',
      'session_added': 'Sesión añadida',
      'history_title': 'Historial de sesiones',
      'history_empty': 'No hay sesiones en el rango seleccionado.',
      'mode_manual': 'Manual',
      'mode_auto': 'Inicio/Detener',
      'edit': 'Editar',
      'delete': 'Eliminar',
      'export': 'Exportar',
      'import': 'Importar',
      'edit_session': 'Editar sesión',
      'edit_session_title': 'Editar sesión',
      'cancel': 'Cancelar',
      'cancel_btn': 'Cancelar',
      'save': 'Guardar',
      'save_btn': 'Guardar',
      'add_btn': 'Añadir',
      'error_edit_time': 'Horas incorrectas (formato HH:MM).',
      'session_running_from': 'Sesión desde: ',
      'field_type': 'Tipo: ',
      'field_mode': 'Modo: ',
      'session_deleted': 'Sesión eliminada',
      'session_updated': 'Sesión actualizada',
      'export_ok': 'Exportado OK: ',
      'export_error': 'Error de exportación: ',
      'export_success': 'Exportado a',
      'backup_missing': 'No hay archivo de copia de seguridad.',
      'import_ok': 'Sesiones importadas: ',
      'import_error': 'Error de importación: ',
      'import_success': 'Importación exitosa',
      'no_files_to_import': 'No hay archivos para importar',
      'choose_file_to_import': 'Elige archivo para importar',
      'backup_saved': 'Copia de seguridad guardada',
      'change_background': 'Cambiar fondo',
      'remove_background': 'Eliminar fondo',
      'icon_color_picker': 'Color de iconos',
      'slide_to_change_color': 'Desliza para cambiar el color',
      'goals_title': 'Mis Objetivos',
      'add_goal': 'Añadir objetivo',
      'no_goals': '¡Sin objetivos. Añade el primero!',
      'goal_name': 'Nombre del objetivo',
      'goal_name_hint': 'ej. Aprender inglés',
      'goal_hours': 'Objetivo en horas',
      'goal_hours_hint': 'ej. 10',
      'goal_period': 'Período',
      'goal_week': 'Semana',
      'goal_month': 'Mes',
      'goal_type': 'Tipo',
      'goal_all_types': 'Todos',
      'goal_added': '¡Objetivo añadido!',
      'goal_deleted': 'Objetivo eliminado',
      'goal_completed': '¡Objetivo alcanzado! ¡Excelente trabajo!',
      'goal_remaining': 'Faltan {hours}h para el objetivo',
      'goal_progress': '{current}h / {target}h',
      'goal_invalid_hours': 'Ingresa un número válido de horas',
      'games_tab': 'Juegos',
      'memory_game_title': 'Juego de Memoria',
      'new_game': 'Nuevo juego',
      'time': 'Tiempo',
      'moves': 'Movimientos',
      'record': 'Récord',
      'congratulations': '¡Felicitaciones! 🎉',
      'game_completed': '¡Has completado el juego!',
      'new_time_record': '¡NUEVO RÉCORD DE TIEMPO!',
      'new_moves_record': '¡NUEVO RÉCORD DE MOVIMIENTOS!',
      'play_again': 'Jugar de nuevo',
      'game_instructions': '¡Encuentra todos los pares! Toca una carta para revelarla.',
      'your_records': '🏆 Tus récords:',
      'best_time': 'Mejor tiempo:',
      'fewest_moves': 'Menos movimientos:',
      'choose_game': 'Elige un juego',
      'games_subtitle': 'Relájate entre sesiones de trabajo',
      'memory_game_desc': '¡Encuentra todos los pares de cartas!',
      'coming_soon': '¡Próximamente!',
      'memory_level_easy': 'Fácil (4x3, 6 pares)',
      'memory_level_medium': 'Medio (4x4, 8 pares)',
      'memory_level_hard': 'Difícil (4x5, 10 pares)',
      'memory_level_advanced': 'Avanzado (4x6, 12 pares)',
      'memory_level_expert': 'Experto (5x6, 15 pares)',
      'memory_level_master': 'Maestro (5x8, 18 pares)',
      'memory_level_legend': 'Leyenda (5x8, 20 pares)',
      'memory_level_epic': 'Épico (5x9, 22 pares)',
      'memory_level_nightmare': 'Pesadilla (5x10, 24 pares)',
      'memory_level_impossible': 'Imposible (5x10, 25 pares)',
      'memory_choose_level': 'Elige la dificultad',
      'memory_locked': 'Nivel bloqueado. Primero completa el anterior.',
      'sudoku_game_title': 'Sudoku',
      'sudoku_game_desc': '¡Rellena la cuadrícula 9x9 con números!',
      'sudoku_choose_level': 'Elige nivel de Sudoku',
      'sudoku_level_1': 'Nivel 1 - Principiante',
      'sudoku_level_2': 'Nivel 2 - Fácil',
      'sudoku_level_3': 'Nivel 3 - Fácil medio',
      'sudoku_level_4': 'Nivel 4 - Medio',
      'sudoku_level_5': 'Nivel 5 - Medio difícil',
      'sudoku_level_6': 'Nivel 6 - Difícil',
      'sudoku_level_7': 'Nivel 7 - Muy difícil',
      'sudoku_level_8': 'Nivel 8 - Experto',
      'sudoku_level_9': 'Nivel 9 - Maestro',
      'sudoku_level_10': 'Nivel 10 - Imposible',
      'sudoku_locked': 'Nivel bloqueado. Primero completa el anterior.',
      'sudoku_congratulations': '¡Sudoku completado! 🎉',
      'sudoku_new_game': 'Nuevo juego',
      'sudoku_check': 'Comprobar',
      'sudoku_errors': 'Errores',
      'sudoku_hint': 'Pista',
      'sudoku_hints_left': 'Pistas',
      'sudoku_solved': '¡Resuelto!',
      'sudoku_mistake': '¡Error! Inténtalo de nuevo.',
      'sudoku_best_time': 'Mejor tiempo',
      'events_tab': 'Eventos',
      'events_title': 'Calendario de Eventos',
      'add_event': 'Añadir evento',
      'no_events': 'No hay eventos programados',
      'event_title': 'Título del evento',
      'event_title_hint': 'ej. Reunión, Entrenamiento',
      'event_date': 'Fecha y hora',
      'event_category': 'Categoría',
      'event_notes': 'Notas',
      'event_notes_hint': 'Información adicional (opcional)',
      'event_reminder': 'Recordatorio',
      'event_category_other': 'Otro',
      'event_category_custom': 'Escribe el nombre de la categoría',
      'event_category_custom_hint': 'ej. Reunión, Estudio, Compras',
      'event_added': '¡Evento añadido!',
      'event_updated': 'Evento actualizado',
      'event_deleted': 'Evento eliminado',
      'reminder_before': 'antes',
      'reminder_day': 'día antes',
      'reminder_2days': '2 días antes',
      'reminder_week': 'semana antes',
      'start_from_event': 'INICIAR desde evento',
      'today_events': 'Hoy',
      'upcoming_events': 'Próximos',
      'past_events': 'Pasados',
      'pomodoro_tab': 'Pomodoro',
      'pomodoro_title': 'Temporizador Pomodoro',
      'pomodoro_work': 'Trabajo',
      'pomodoro_break': 'Descanso',
      'pomodoro_long_break': 'Descanso largo',
      'pomodoro_start': 'Iniciar',
      'pomodoro_pause': 'Pausar',
      'pomodoro_reset': 'Reiniciar',
      'pomodoro_sessions': 'Sesiones',
      'pomodoro_settings': 'Ajustes',
      'pomodoro_work_time': 'Tiempo de trabajo (min)',
      'pomodoro_break_time': 'Tiempo de descanso (min)',
      'pomodoro_long_break_time': 'Descanso largo (min)',
      'pomodoro_sessions_until_long': 'Sesiones hasta descanso largo',
      'pet_tab': 'Pet',
      'pet_title': 'DevPet 🐾',
      'pet_feed_btn': 'Alimentar',
      'pet_daily_xp': 'XP diario',
      'pet_daily_max': '✅ ¡Máx!',
      'pet_daily_tip': '1 XP por cada 5 min de estudio. Máx 100 XP al día.',
      'pet_daily_done': '🎉 ¡Buen trabajo! Mañana puedes ganar más XP.',
      'pet_stats_total_xp': 'XP total',
      'pet_stats_collection': 'Colección',
      'pet_stats_stage': 'Etapa',
      'pet_rewards_title': 'Premios por colección',
      'pet_tips_title': '¿Cómo funciona?',
      'pet_tip_1': 'Trabaja/estudia — ganas 1 XP por cada 5 minutos',
      'pet_tip_2': 'Máx 100 XP al día — el límite se reinicia a medianoche',
      'pet_tip_3': 'Con 1000 XP la mascota se jubila',
      'pet_tip_4': '¡Colecciona las 10 mascotas y desbloquea premios!',
      'pet_tip_5': 'Alimenta tu mascota — la energía baja si no trabajas',
      'pet_collection_title': '🏆 Colección de Mascotas',
      'pet_collection_current': 'Actual',
      'pet_reward_unlocked': '🎊 ¡Premio desbloqueado!',
      'pet_reward_btn': '¡Genial! 🎉',
      'pet_snack_fed': '¡alimentado! +15 energía 🍎',
      'pet_limit_reached': '😴 ¡Límite de XP de hoy alcanzado!',
      'pet_stage_egg': 'Huevo',
      'pet_stage_baby': 'Bebé',
      'pet_stage_junior': 'Junior',
      'pet_stage_senior': 'Senior',
      'pet_stage_master': 'Maestro',
      'pet_stage_retired': 'Jubilado',
      'pet_enable_title': 'Activar DevPet',
      'pet_enable_subtitle': 'Cuida tu mascota virtual y gana XP estudiando',
      'pet_enable_btn': 'Activar DevPet 🐾',
      'notes_tab': 'Bloc de Notas de Voz',
      'notes_edit_title': '✏️ Editar nota',
      'notes_cancel': 'Cancelar',
      'notes_save': 'Guardar',
      'notes_delete_all': '¿Eliminar todas?',
      'notes_delete_confirm': 'Esta operación no se puede deshacer.',
      'notes_delete_btn': 'Eliminar',
      'notes_recording': 'Grabando...',
      'notes_ready': 'Listo para grabar',
      'notes_tap_to_record': 'Pulsa el micrófono y habla...',
      'notes_tap_to_stop': 'Toca para detener',
      'notes_tap_to_start': 'Toca para grabar',
      'notes_empty': 'Sin notas.\nPulsa el micrófono para añadir la primera.',
      'notes_reminder_set': '🔔 Recordatorio:',
      'notes_reminder_cancel': '🔕 Recordatorio cancelado',
      'notes_reminder_tooltip_set': 'Establecer recordatorio',
      'notes_reminder_tooltip_cancel': 'Cancelar recordatorio',
      'reminder_mode_title': 'Modo de recordatorio',
      // ── ALARM ──────────────────────────────────────────────
      'alarm_pick_title': 'Elige el sonido de alarma',
      'alarm_pick_cancel': 'Cancelar',
      'alarm_pick_select': 'Elegir',
      'alarm_reminder_title': '🔔 Recordatorio',
      'alarm_stop': 'PARAR',
      'alarm_test_tooltip': 'Probar alarma',
      'alarm_sound_label': 'Sonido: ',
      'event_reminder_none': 'Sin recordatorio',
      'event_mode_notification': 'Notif.',
      'event_mode_vibration': 'Vibr.',
      'event_mode_alarm': 'Alarma',
      'event_mode_desc_notification': '🔔 Sonido corto del sistema',
      'event_mode_desc_vibration': '📳 Solo vibración, sin sonido',
      'event_mode_desc_alarm': '🚨 Alarma en bucle — funciona con la app cerrada',
      'notification_channel_reminders': 'Recordatorios',
      'notification_channel_reminders_desc': 'Notificaciones de eventos',
      'stats_refreshed': 'Estadísticas actualizadas',
      'refresh_tooltip': 'Actualizar',
      'edit_event': 'Editar evento',
    },

    'en': {
      'app_title': 'Work Study Timer',
      'language': 'Language',
      'range': 'Range',
      'today': 'Today',
      'this_week': 'This week',
      'this_month': 'This month',
      'all': 'All',
      'search_hint': 'Search by description (e.g. Meeting, Study)',
      'instructions_title': 'User Guide',
      'instructions_content':
      'Work Study Timer – track your time, achieve your goals!\n\n'
          '⏱️ 1. TIMER (main tab)\n'
          '• Enter an activity description and choose a category\n'
          '• Tap START to begin a session\n'
          '• Tap STOP to save the session to history\n'
          '• You can also add a session manually – tap "ADD TIME MANUALLY"\n\n'
          '📊 2. SUMMARY\n'
          '• Filter data: Today / This week / This month / All\n'
          '• Bar chart of the last 7 days\n'
          '• Pie chart showing time distribution by category\n'
          '• Detailed statistics with progress bars\n\n'
          '🎯 3. GOALS\n'
          '• Add a weekly or monthly goal\n'
          '• Set the number of hours and category\n'
          '• Track progress on the progress bar\n\n'
          '📅 4. EVENTS\n'
          '• Add planned events with date and time\n'
          '• Set a reminder (5 min – 1 week before)\n'
          '• Categories: Work, Sport, Free time, Other\n\n'
          '🍅 5. POMODORO\n'
          '• Pomodoro technique: 25 min work + 5 min break\n'
          '• Customize work and break times in settings\n'
          '• After 4 sessions, automatic long break\n\n'
          '🎮 6. GAMES\n'
          '• Memory Game – 10 difficulty levels\n'
          '• Sudoku – 10 difficulty levels\n'
          '• Unlock new levels by completing previous ones\n\n'
          '⚙️ 7. SETTINGS (gear icon)\n'
          '• Change app background (your own photo)\n'
          '• Change icon color\n'
          '• Change language: 🇵🇱 Polski / 🇪🇸 Español / 🇬🇧 English\n\n'
          '💾 8. BACKUP\n'
          '• Export data – save backup to your phone\n'
          '• Share backup – send file via email or WhatsApp\n'
          '• Import data – load a previous backup\n\n'
          '🔒 9. PRIVACY\n'
          '• All data is stored locally on your device only',
      'work': 'Work',
      'sport': 'Sport',
      'free_time': 'Free time',
      'type': 'Category',
      'type_instruction': 'Choose your activity category',
      'add_new_type': 'Add new type',
      'add_custom_type_title': 'Add new activity type',
      'custom_type_hint': 'New activity name (e.g. Study, Guitar)',
      'manage_custom_types': 'Manage types',
      'no_custom_types': 'No custom types.',
      'type_name_label': 'Type name',
      'type_exists': 'This type already exists',
      'type_added': 'Type added',
      'type_deleted': 'Type deleted',
      'delete_type': 'Delete type',
      'cannot_delete_default': 'Cannot delete default type',
      'quick_timer': 'Quick timer',
      'description_hint': 'Description (optional)',
      'start_btn': 'Start',
      'stop_btn': 'Stop',
      'no_active': 'No active session.',
      'close': 'Close',
      'close_btn': 'Close',
      'new_activity_section': 'New activity',
      'start_now_btn': 'START NOW',
      'add_time_range_btn': 'ADD TIME MANUALLY',
      'running_since': 'Running since',
      'summary_title': 'Summary',
      'summary_total': 'Total',
      'last_7_days': 'Last 7 days',
      'time_distribution': 'Time distribution',
      'detailed_summary': 'Detailed summary',
      'avg_per_day': 'Avg/day',
      'best_day': 'Best day',
      'last_30_days': 'Last 30 days',
      'day_mon': 'Mon',
      'day_tue': 'Tue',
      'day_wed': 'Wed',
      'day_thu': 'Thu',
      'day_fri': 'Fri',
      'day_sat': 'Sat',
      'day_sun': 'Sun',
      'no_data': 'No data',
      'date_label': 'Date: ',
      'choose_date': 'Choose date',
      'description_label': 'What will you do? (e.g. Running, Study)',
      'start_time_label': 'Start (HH:MM)',
      'end_time_label': 'End (HH:MM)',
      'start_time_hint': 'e.g. 08:30',
      'end_time_hint': 'e.g. 10:15',
      'add_session_btn': 'Add session',
      'no_description': 'No description',
      'error_time_format': 'Check times (HH:MM format, end after start).',
      'fill_all_fields': 'Fill in all fields',
      'invalid_time_format': 'Invalid time format (use HH:MM)',
      'session_added': 'Session added',
      'history_title': 'Session history',
      'history_empty': 'No sessions in selected range.',
      'mode_manual': 'Manual',
      'mode_auto': 'Start/Stop',
      'edit': 'Edit',
      'delete': 'Delete',
      'export': 'Export',
      'import': 'Import',
      'edit_session': 'Edit session',
      'edit_session_title': 'Edit session',
      'cancel': 'Cancel',
      'cancel_btn': 'Cancel',
      'save': 'Save',
      'save_btn': 'Save',
      'add_btn': 'Add',
      'error_edit_time': 'Wrong times (HH:MM format, end after start).',
      'session_running_from': 'Session running since: ',
      'field_type': 'Type: ',
      'field_mode': 'Mode: ',
      'session_deleted': 'Session deleted',
      'session_updated': 'Session updated',
      'export_ok': 'Export OK: ',
      'export_error': 'Export error: ',
      'export_success': 'Exported to',
      'backup_missing': 'No backup file found!',
      'import_ok': 'Sessions imported: ',
      'import_error': 'Import error: ',
      'import_success': 'Import successful',
      'no_files_to_import': 'No files to import',
      'choose_file_to_import': 'Choose file to import',
      'backup_saved': 'Backup saved',
      'change_background': 'Change background',
      'remove_background': 'Remove background',
      'icon_color_picker': 'Icon color',
      'slide_to_change_color': 'Slide to change color',
      'goals_title': 'My Goals',
      'add_goal': 'Add goal',
      'no_goals': 'No goals. Add your first goal!',
      'goal_name': 'Goal name',
      'goal_name_hint': 'e.g. Learn Spanish',
      'goal_hours': 'Goal in hours',
      'goal_hours_hint': 'e.g. 10',
      'goal_period': 'Period',
      'goal_week': 'Week',
      'goal_month': 'Month',
      'goal_type': 'Type',
      'goal_all_types': 'All',
      'goal_added': 'Goal added!',
      'goal_deleted': 'Goal deleted',
      'goal_completed': 'Goal achieved! Great job!',
      'goal_remaining': '{hours}h left to goal',
      'goal_progress': '{current}h / {target}h',
      'goal_invalid_hours': 'Enter a valid number of hours',
      'games_tab': 'Games',
      'memory_game_title': 'Memory Game',
      'new_game': 'New game',
      'time': 'Time',
      'moves': 'Moves',
      'record': 'Record',
      'congratulations': 'Congratulations! 🎉',
      'game_completed': 'You completed the game!',
      'new_time_record': '🏆 NEW TIME RECORD!',
      'new_moves_record': '🏆 NEW MOVES RECORD!',
      'play_again': 'Play again',
      'game_instructions': 'Find all pairs! Tap a card to reveal it.',
      'your_records': '🏆 Your records:',
      'best_time': 'Best time:',
      'fewest_moves': 'Fewest moves:',
      'choose_game': 'Choose a game',
      'games_subtitle': 'Relax between work sessions',
      'memory_game_desc': 'Find all matching card pairs!',
      'coming_soon': 'Coming soon!',
      'memory_level_easy': 'Easy (4x3, 6 pairs)',
      'memory_level_medium': 'Medium (4x4, 8 pairs)',
      'memory_level_hard': 'Hard (4x5, 10 pairs)',
      'memory_level_advanced': 'Advanced (4x6, 12 pairs)',
      'memory_level_expert': 'Expert (5x6, 15 pairs)',
      'memory_level_master': 'Master (5x8, 18 pairs)',
      'memory_level_legend': 'Legend (5x8, 20 pairs)',
      'memory_level_epic': 'Epic (5x9, 22 pairs)',
      'memory_level_nightmare': 'Nightmare (5x10, 24 pairs)',
      'memory_level_impossible': 'Impossible (5x10, 25 pairs)',
      'memory_choose_level': 'Choose level',
      'memory_locked': 'Level locked. Complete the previous one first.',
      'sudoku_game_title': 'Sudoku',
      'sudoku_game_desc': 'Fill the 9x9 grid with numbers!',
      'sudoku_choose_level': 'Choose Sudoku level',
      'sudoku_level_1': 'Level 1 - Beginner',
      'sudoku_level_2': 'Level 2 - Easy',
      'sudoku_level_3': 'Level 3 - Easy medium',
      'sudoku_level_4': 'Level 4 - Medium',
      'sudoku_level_5': 'Level 5 - Medium hard',
      'sudoku_level_6': 'Level 6 - Hard',
      'sudoku_level_7': 'Level 7 - Very hard',
      'sudoku_level_8': 'Level 8 - Expert',
      'sudoku_level_9': 'Level 9 - Master',
      'sudoku_level_10': 'Level 10 - Impossible',
      'sudoku_locked': 'Level locked. Complete the previous one first.',
      'sudoku_congratulations': 'Sudoku completed! 🎉',
      'sudoku_new_game': 'New game',
      'sudoku_check': 'Check',
      'sudoku_errors': 'Errors',
      'sudoku_hint': 'Hint',
      'sudoku_hints_left': 'Hints',
      'sudoku_solved': 'Solved!',
      'sudoku_mistake': 'Mistake! Try again.',
      'sudoku_best_time': 'Best time',
      'events_tab': 'Events',
      'events_title': 'Events Calendar',
      'add_event': 'Add event',
      'no_events': 'No scheduled events',
      'event_title': 'Event title',
      'event_title_hint': 'e.g. Meeting, Training',
      'event_date': 'Date and time',
      'event_category': 'Category',
      'event_notes': 'Notes',
      'event_notes_hint': 'Additional information (optional)',
      'event_reminder': 'Reminder',
      'event_category_other': 'Other',
      'event_category_custom': 'Enter category name',
      'event_category_custom_hint': 'e.g. Meeting, Study, Shopping',
      'event_added': 'Event added!',
      'event_updated': 'Event updated',
      'event_deleted': 'Event deleted',
      'reminder_before': 'before',
      'reminder_day': 'day before',
      'reminder_2days': '2 days before',
      'reminder_week': 'week before',
      'start_from_event': 'START from event',
      'today_events': 'Today',
      'upcoming_events': 'Upcoming',
      'past_events': 'Past',
      'pomodoro_tab': 'Pomodoro',
      'pomodoro_title': 'Pomodoro Timer',
      'pomodoro_work': 'Work',
      'pomodoro_break': 'Break',
      'pomodoro_long_break': 'Long break',
      'pomodoro_start': 'Start',
      'pomodoro_pause': 'Pause',
      'pomodoro_reset': 'Reset',
      'pomodoro_sessions': 'Sessions',
      'pomodoro_settings': 'Settings',
      'pomodoro_work_time': 'Work time (min)',
      'pomodoro_break_time': 'Break time (min)',
      'pomodoro_long_break_time': 'Long break (min)',
      'pomodoro_sessions_until_long': 'Sessions until long break',
      'pet_tab': 'Pet',
      'pet_title': 'DevPet 🐾',
      'pet_feed_btn': 'Feed',
      'pet_daily_xp': 'Daily XP',
      'pet_daily_max': '✅ Max!',
      'pet_daily_tip': '1 XP per 5 min of study. Max 100 XP per day.',
      'pet_daily_done': '🎉 Great job! Come back tomorrow for more XP.',
      'pet_stats_total_xp': 'Total XP',
      'pet_stats_collection': 'Collection',
      'pet_stats_stage': 'Stage',
      'pet_rewards_title': 'Collection Rewards',
      'pet_tips_title': 'How it works?',
      'pet_tip_1': 'Work/study — earn 1 XP for every 5 minutes',
      'pet_tip_2': 'Max 100 XP per day — limit resets at midnight',
      'pet_tip_3': 'At 1000 XP your pet retires to the collection',
      'pet_tip_4': 'Collect all 10 pets and unlock rewards!',
      'pet_tip_5': 'Feed your pet — energy drops when you stop working',
      'pet_collection_title': '🏆 Pet Collection',
      'pet_collection_current': 'Current',
      'pet_reward_unlocked': '🎊 Reward unlocked!',
      'pet_reward_btn': 'Awesome! 🎉',
      'pet_snack_fed': 'fed! +15 energy 🍎',
      'pet_limit_reached': '😴 Daily XP limit reached!',
      'pet_stage_egg': 'Egg',
      'pet_stage_baby': 'Baby',
      'pet_stage_junior': 'Junior',
      'pet_stage_senior': 'Senior',
      'pet_stage_master': 'Master',
      'pet_stage_retired': 'Retired',
      'pet_enable_title': 'Enable DevPet',
      'pet_enable_subtitle': 'Take care of a virtual pet and earn XP by studying',
      'pet_enable_btn': 'Enable DevPet 🐾',
      'notes_tab': 'Voice Notes',
      'notes_edit_title': '✏️ Edit note',
      'notes_cancel': 'Cancel',
      'notes_save': 'Save',
      'notes_delete_all': 'Delete all?',
      'notes_delete_confirm': 'This action cannot be undone.',
      'notes_delete_btn': 'Delete',
      'notes_recording': 'Recording...',
      'notes_ready': 'Ready to record',
      'notes_tap_to_record': 'Tap the microphone and speak...',
      'notes_tap_to_stop': 'Tap to stop',
      'notes_tap_to_start': 'Tap to record',
      'notes_empty': 'No notes.\nTap the microphone to add the first one.',
      'notes_reminder_set': '🔔 Reminder:',
      'notes_reminder_cancel': '🔕 Reminder cancelled',
      'notes_reminder_tooltip_set': 'Set reminder',
      'notes_reminder_tooltip_cancel': 'Cancel reminder',
      'reminder_mode_title': 'Reminder mode',
      // ── ALARM ──────────────────────────────────────────────
      'alarm_pick_title': 'Choose alarm sound',
      'alarm_pick_cancel': 'Cancel',
      'alarm_pick_select': 'Select',
      'alarm_reminder_title': '🔔 Reminder',
      'alarm_stop': 'STOP',
      'alarm_test_tooltip': 'Test alarm',
      'alarm_sound_label': 'Sound: ',
      'event_reminder_none': 'No reminder',
      'event_mode_notification': 'Notif.',
      'event_mode_vibration': 'Vibr.',
      'event_mode_alarm': 'Alarm',
      'event_mode_desc_notification': '🔔 Short system sound',
      'event_mode_desc_vibration': '📳 Vibration only, no sound',
      'event_mode_desc_alarm': '🚨 Looping alarm — works when app is closed',
      'notification_channel_reminders': 'Reminders',
      'notification_channel_reminders_desc': 'Event notifications',
      'stats_refreshed': 'Statistics updated',
      'refresh_tooltip': 'Refresh',
      'edit_event': 'Edit event',
    },
  };

  /// Returns translation for [key] in [languageCode] without BuildContext.
  static String getTranslation(String languageCode, String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        _localizedValues['pl']?[key] ??
        key;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        _localizedValues['pl']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['pl', 'es', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}